# 新增代码：配置ETF数据源 (原配置已注释保留)
qlib_init:
    # provider_uri: "~/.qlib/qlib_data/cn_data"  # 原官方数据源
    provider_uri: "/Users/handsomedoge/Documents/CITIC_quant/qlib_etf_data_final"
    region: cn

# market: &market csi300  # 原CSI300
# benchmark: &benchmark SH000300  # 原基准
market: &market all  # 使用所有ETF数据
benchmark: &benchmark 000852.csi  # 中证1000作为基准

data_handler_config: &data_handler_config
    # 新增代码：调整时间范围匹配ETF数据 (2015-2025)
    start_time: 2015-01-01  # 原: 2008-01-01
    end_time: 2025-07-10    # 修改：从2025-07-15改为2025-07-10，避免IndexError
    fit_start_time: 2015-01-01  # 原: 2008-01-01  
    fit_end_time: 2020-12-31    # 原: 2014-12-31
    instruments: *market
    # 移除data_loader配置，Alpha158不需要
    
    infer_processors:
        - class: RobustZScoreNorm
          kwargs:
              fields_group: feature
              clip_outlier: true
              fit_start_time: 2008-01-01
              fit_end_time: 2014-12-31
        - class: Fillna
          kwargs:
              fields_group: feature
    learn_processors:
        - class: DropnaLabel
        - class: CSZScoreNorm
          kwargs:
              fields_group: label

port_analysis_config: &port_analysis_config
    strategy:
        class: TopkDropoutStrategy
        module_path: qlib.contrib.strategy
        kwargs:
            signal: <PRED>
            topk: 50
            n_drop: 5
    backtest:
        # 新增代码：调整回测时间段匹配ETF数据  
        start_time: 2023-01-01  # 原: 2017-01-01
        end_time: 2025-07-10    # 修改：从2025-07-15改为2025-07-10，避免IndexError
        account: 100000000
        benchmark: *benchmark
        exchange_kwargs:
            limit_threshold: 0.095
            deal_price: close
            open_cost: 0.0005
            close_cost: 0.0015
            min_cost: 5

task:
    model:
        class: GeneralPTNN
        module_path: qlib.contrib.model.pytorch_general_nn
        kwargs:
            n_epochs: {{ n_epochs }}
            lr: {{ lr }}
            early_stop: {{ early_stop }}
            batch_size: {{ batch_size }}
            weight_decay: {{ weight_decay }}
            metric: loss
            loss: mse
            n_jobs: 20
            GPU: 0
            pt_model_uri: "model.model_cls"
            pt_model_kwargs: {
                "num_features": {{ num_features }}{% if num_timesteps %}, "num_timesteps": {{ num_timesteps }}{% endif %}
            }
    dataset:
        class: {{ dataset_cls | default("DatasetH") }}
        module_path: qlib.data.dataset
        kwargs:
            handler:
                # 新增代码：使用Alpha158处理器，更成熟稳定，避免data_loader问题
                class: Alpha158
                module_path: qlib.contrib.data.handler
                kwargs: *data_handler_config
            segments:
                # 新增代码：调整训练测试时间段匹配ETF数据
                train: [2015-01-01, 2020-12-31]  # 原: [2008-01-01, 2014-12-31]
                valid: [2021-01-01, 2022-12-31]   # 原: [2015-01-01, 2016-12-31] 
                test: [2023-01-01, 2025-07-10]    # 修改：从2025-07-15改为2025-07-10，避免IndexError
            {% if step_len %}step_len: {{ step_len }}{% endif %}
    record: 
        - class: SignalRecord
          module_path: qlib.workflow.record_temp
          kwargs: 
            model: <MODEL>
            dataset: <DATASET>
        - class: SigAnaRecord
          module_path: qlib.workflow.record_temp
          kwargs: 
            ana_long_short: False
            ann_scaler: 252
        - class: PortAnaRecord
          module_path: qlib.workflow.record_temp
          kwargs: 
            config: *port_analysis_config
