#!/usr/bin/env python3
"""
Convert all combined_factors_df.parquet files to .pkl format
Auto-generated by test_parquet_vs_pkl.py
"""

import pandas as pd
from pathlib import Path
import shutil

def convert_all_parquet_to_pkl():
    workspace_path = Path("/Users/handsomedoge/Documents/CITIC_quant/RD-Agent/git_ignore_folder/RD-Agent_workspace")
    
    parquet_files = list(workspace_path.glob("*/combined_factors_df.parquet"))
    print(f"Found {len(parquet_files)} parquet files to convert")
    
    converted = 0
    errors = 0
    
    for parquet_file in parquet_files:
        pkl_file = parquet_file.with_suffix('.pkl')
        backup_file = parquet_file.with_suffix('.parquet.bak')
        
        try:
            print(f"\nConverting {parquet_file.parent.name}/...")
            
            # Read parquet
            df = pd.read_parquet(parquet_file)
            
            # Save as pkl
            df.to_pickle(pkl_file)
            
            # Backup original
            shutil.copy2(parquet_file, backup_file)
            
            # Remove original
            parquet_file.unlink()
            
            print(f"  ✅ Converted successfully")
            print(f"  📁 Backup saved as {backup_file.name}")
            converted += 1
            
        except Exception as e:
            print(f"  ❌ Error: {e}")
            errors += 1
    
    print(f"\n{'='*60}")
    print(f"Conversion complete: {converted} succeeded, {errors} failed")
    
    if converted > 0:
        print("\n⚠️  IMPORTANT: Update configuration files to reference .pkl instead of .parquet")

if __name__ == "__main__":
    convert_all_parquet_to_pkl()
